export const LATEST_CONVERSATION_BRIEF = [
  "# Latest Conversation Brief",
  "",
  "最后更新：2026-05-08",
  "",
  "## 用途",
  "",
  "这份 Brief 用于把这次对话框里已经明确下来的主要任务、交付标准、Git 同步规则和无缝交接要求，直接复制给其他 AI 对话框复刻执行。",
  "重点不是只让 AI 操作 Git，而是让它把项目源码、项目状态、开发进展、下一步规划和交接文档一起维护好。",
  "",
  "## 项目身份",
  "",
  "- 项目名：`QiuQiuTech`",
  "- GitHub 仓库：`alexll000/QiuQiuTech`",
  "- 默认分支：`main`",
  "- 本地仓库根目录：`$QIQIUTECH_ROOT`",
  "",
  "## 这次对话的核心任务",
  "",
  "用户的真实需求不是单次 push，而是：",
  "",
  "1. 把当前项目同步到 GitHub",
  "2. 保证另一台电脑 `git clone` 后能继续开发",
  "3. 把项目的最新进展、当前状态、下一步计划、整体规划写进仓库",
  "4. 把这次对话沉淀成可交接给下一个 AI 的 Brief / handoff 文档",
  "5. 以后用户说“更新 git”，默认按固定动作做全套同步，不再只 push 代码",
  "",
  "## 用户的固定要求",
  "",
  "以后只要用户说这些话：",
  "",
  "- “更新 git”",
  "- “同步 GitHub”",
  "- “把项目同步到 GitHub”",
  "- “更新仓库”",
  "",
  "都默认理解为以下固定动作：",
  "",
  "1. 同步最新代码",
  "2. 更新最新进展",
  "3. 更新当前状态",
  "4. 更新下一步计划",
  "5. 更新整体规划",
  "6. 更新 AI 交接文档",
  "7. 检查是否存在未同步的真实业务文件",
  "8. 最后再 commit / push",
  "",
  "## Git 同步的标准流程",
  "",
  "每次同步 Git，固定按这个顺序执行：",
  "",
  "1. `git status --short --ignored`",
  "2. 检查 `untracked` 里是否有真实源码 / 文档 / API route / `.env.example`",
  "3. 区分三类文件：",
  "   - 必须同步：源码、文档、README、配置样板",
  "   - 不该同步：`node_modules`、`.next`、缓存、系统垃圾文件",
  "   - 需要谨慎处理：私有密钥、本地运行数据、真实账号配置",
  "4. 更新交接文档",
  "5. 提交前再次核对本地真实文件和 Git 已跟踪文件是否存在关键差异",
  "6. commit",
  "7. push",
  "8. push 后核对远端 `main` 最新 commit 是否一致",
  "",
  "## 无缝衔接的定义",
  "",
  "这次对话里，“无缝衔接”已经被明确为：",
  "",
  "**另一台电脑拉下仓库后，不会因为缺源码、缺关键文档、缺配置样板、缺开发说明而断档，可以直接继续开发。**",
  "",
  "这里的“无缝”指的是：",
  "",
  "- 源码无缺失",
  "- 文档无缺失",
  "- handoff 无缺失",
  "- 启动方式明确",
  "",
  "不包含：",
  "",
  "- 自动带过去 `node_modules`",
  "- 自动带过去 `.next`",
  "- 自动复制本地运行中的 Docker / Postgres / Directus 状态",
  "",
  "## 当前已经完成的关键结果",
  "",
  "### 1. GitHub 同步",
  "",
  "项目已经同步到：",
  "",
  "- [alexll000/QiuQiuTech](https://github.com/alexll000/QiuQiuTech)",
  "",
  "### 2. 根仓库已经建立",
  "",
  "现在真正的主仓库是根目录 `QiuQiuTech/`，不再只是 `web/` 子目录单独管理。",
  "",
  "### 3. 交接文档已经补齐",
  "",
  "当前关键交接文件包括：",
  "",
  "- `README.md`",
  "- `docs/ai-handoff.md`",
  "- `docs/current-build-status.md`",
  "- `docs/Git-sync-handoff-brief.md`",
  "- `docs/Latest-conversation-brief.md`",
  "",
  "### 4. 当前源码状态已可继续开发",
  "",
  "已补齐：",
  "",
  "- `web/.env.example`",
  "- `web/src/app/api/...` 本地 API 契约路由",
  "- `web/src/lib/action-service.ts`",
  "- `web/src/lib/mock-action-service.ts`",
  "- `workflow-service` 相关说明",
  "- Directus 初始化清单补充项",
  "",
  "### 5. 本地验证已完成",
  "",
  "已验证：",
  "",
  "- `web` 的 `npm run lint` 通过",
  "- `web` 的 `npm run build` 通过",
  "",
  "## 当前项目状态摘要",
  "",
  "截至 2026-05-08，QiuQiuTech 当前具备：",
  "",
  "1. 前端公开站点框架",
  "2. 首页、内容、事件、玩法、专题、合作、投稿、榜单、登录、用户中心、后台入口骨架",
  "3. SEO 基建",
  "4. Directus 接入预留层",
  "5. 用户中心工作台 mock 数据层",
  "6. 投稿中心与合作申请流程蓝图",
  "7. 收藏 / 通知已读 / 保存草稿 / 申请合作的本地动作接口壳层",
  "",
  "## 当前未完成重点",
  "",
  "1. Directus 真实接通",
  "2. 投稿真实表单提交",
  "3. 合作申请真实流程",
  "4. 用户中心真实账户数据",
  "5. 抓取和导入流程",
  "6. 后台审核流真实落地",
  "",
  "## 另一台电脑如何继续开发",
  "",
  "前台：",
  "",
  "```bash",
  "cd \"$QIQIUTECH_ROOT/web\"",
  "npm install",
  "cp .env.example .env.local",
  "npm run dev",
  "```",
  "",
  "CMS：",
  "",
  "```bash",
  "cd \"$QIQIUTECH_ROOT/cms\"",
  "cp .env.example .env",
  "docker compose up -d",
  "```",
  "",
  "## 另一个 AI 接手时必须先读",
  "",
  "1. `README.md`",
  "2. `docs/ai-handoff.md`",
  "3. `docs/current-build-status.md`",
  "4. `docs/Git-sync-handoff-brief.md`",
  "5. `docs/Latest-conversation-brief.md`",
  "6. `docs/directus-initialization-checklist.md`",
  "7. `web/README.md`",
  "8. `cms/README.md`",
  "",
  "## 对接手 AI 的明确要求",
  "",
  "不要只做这些：",
  "",
  "- 只看 `git status`",
  "- 只 push 已提交内容",
  "- 只同步 `web/`",
  "- 只改代码不改文档",
  "",
  "必须做到：",
  "",
  "1. 保证仓库可继续开发",
  "2. 保证文档可交接",
  "3. 保证状态可追踪",
  "4. 保证下一个 AI 拉下来后能迅速接手",
  "5. 如果发现本地还有未提交的真实业务文件，必须先补进去再 push",
].join("\n");
